### ISSUE TITLE
No reconoce la extensión

### ISSUE THREAD

**Issue by jhossettstalinn** [sebastian-correa/ulauncher-rae-dle#1]
Cuando ingreso la extensión URL no sucede nada; es como si no lo reconociera.

**Comment by sebastian-correa** [comment]
Hola!

Podes adjuntar un screenshot?

Gracias!

**Comment by jhossettstalinn** [comment]
Buenas noches. Esto sucede:

![Screenshot from 2021-07-08 23-14-41](https://user-images.githubusercontent.com/45399284/125023205-facb7300-e043-11eb-8f3f-98b04bdd7956.png)
Fig. 1  Agregando la extensión URL.
![Screenshot from 2021-07-08 23-15-12](https://user-images.githubusercontent.com/45399284/125023351-585fbf80-e044-11eb-921d-f069a18e0ad8.png)
Fig. 2 No pasa nada después de agregar la extensión.

También intenté instalar manualmente la extensión y esto es lo que arrojo la terminal cuando ejecuté el archivo main.py con python3:
![Screenshot from 2021-07-08 23-50-39](https://user-images.githubusercontent.com/45399284/125025252-f4d79100-e047-11eb-9b18-a7b9060c9dc1.png)

Pero ahora en Ulauncher me aparece esto:
![Screenshot from 2021-07-08 23-44-19](https://user-images.githubusercontent.com/45399284/125024559-a4136880-e046-11eb-9f71-30f280e4e61c.png)

**Comment by sebastian-correa** [comment]
@jhossettstalinn gracias por tu paciencia! Esto es nuevo para mi y estaba esperando que me llegase un email notificando tu comentario como la última vez, pero nunca llegó.

No se como solucionar el error que te da al ejecutar `main.py` manualmente. Mientras escribo código, mi linter se queja todo el tiempo de que no encunetra el paquete de uLauncher, pero todo funciona bien al correr uLauncher.

Cerrá uLauncher manualmente y en la consola escribí:
```
cd ~/.local/share/ulauncher/extensions
git clone https://github.com/sebastian-correa/ulauncher-rae-dle.git
```

Abrí uLauncher como harías normalmente y debiera andar. Podes probar con `rae diccionario`.

En cuanto descubra el problema con el link, lo soluciono. Por alguna razón está dando un error 422 al solicitar la extensión.

**Comment by sebastian-correa** [comment]
@jhossettstalinn Podes probar instalar la extensión con el link ahora?

Creo que habia un problema con `versions.json` y `manifest.json` que solucioné.

En mi computadora la instalación con link funciona bien ahora.

**Comment by jhossettstalinn** [comment]
@sebastian-correa Hola. Recien veo los correos...
Instalé la extensión con el link y ando; ahora funciona sin ningún problema. Muchisimas gracias, necesitaba esta extensión. 
![image](https://user-images.githubusercontent.com/45399284/125178153-ae00ad00-e1a7-11eb-94a0-e882e07ecbc5.png)

**Comment by sebastian-correa** [comment]
@jhossettstalinn Genial! Voy a maracar como cerrada la issue.

Aun debo escribir el readme, pero te adelanto: con Enter copias la definicion que tengas seleccionada y Alt+Enter te lleva a la RAE.
