### ISSUE TITLE
Feature request: open the drae website on the given word when tapping enter

### ISSUE THREAD

**Issue by luispabon** [sebastian-correa/ulauncher-rae-dle#2]
As per title really, It'd be great if when pressing enter on the definition the DRAE website would open on it. For instance, for `cojones`, the DRAE form (and this extension) seem to resolve it to `cojón`, which lives at this page: https://dle.rae.es/coj%C3%B3n

**Comment by sebastian-correa** [comment]
@luispabon if I didn't misunderstand, <kbd>Alt</kbd> + <kbd>Enter</kbd> does exactly that, while <kbd>Enter</kbd> copies the definition to the clipboard ([see 2) ii.](https://github.com/sebastian-correa/ulauncher-rae-dle#uso)).

Can you confirm that <kbd>Alt</kbd> + <kbd>Enter</kbd> does what you want?

Notwithstanding your response, with the search for `cojones`, DRAE returns a list of lists of definitions and the extension only seems to keep the first definition but matches it with your search term (which might not match exactly). This is the reason why <kbd>Alt</kbd> + <kbd>Enter</kbd> takes you to /cojones and not to /coj%C3%B3n. I will try to make the extension handle this cases better.

**Comment by sebastian-correa** [comment]
@luispabon can you check if the extension now does what you expected it to do? Please keep in mind that the correct shortcut to open the browser is <kbd>Alt</kbd> + <kbd>Enter</kbd>.

When looking for `cojones`, you should now see a longer list of definitions with the different words in the DLE.
![2021-08-06_16-46](https://user-images.githubusercontent.com/43179146/128563766-c162dd0b-4f26-4677-8e6b-61ff2d7db3fd.png)

**Comment by luispabon** [comment]
Thanks for your work on this, Sebastián. The extra definitions are a massive, clear improvement and alt+enter indeed opens DRAE's website at the given word - apologies I missed that in the instructions initially 👍🏽 💪🏽

**Comment by sebastian-correa** [comment]
@luispabon I hope the feature works with all words. The extension needs unit tests and many tests cases, as the structure in the DLE is pretty strange. That's for the future, or for anyone who wants to contribute 😉.

I'm closing the issue, but feel free to reopen if you see fit.

**Comment by luispabon** [comment]
Muchas gracias Sebastian 👍🏽
